### ISSUE TITLE
omas conda-forge version (0.54.0) is not up to date with the feedstock (0.55.1)

### ISSUE THREAD

**Issue by orso82** [conda-forge/omas-feedstock#87]
@smithsp do you understand why 
https://anaconda.org/conda-forge/omas is at v0.54.0 even though version 0.55.1 got merged in the feedstock https://github.com/conda-forge/omas-feedstock/pull/86

**Comment by smithsp** [comment]
Not sure why the timing of this comment corresponds with the time at which the 0.55.1 version became available, but yes it is available now
![image](https://user-images.githubusercontent.com/782050/76609248-f99d3b00-650e-11ea-92cd-97737acad412.png)

**Comment by orso82** [comment]
It must have been triggered by me merging #83
